Squashed commit of the following:
commit 1732d01fa7345b9ed2224d557ecc8a7259cf1af0
Merge: 4d6e3a2 2285d33
Author: lpelkey23 <lpelkey23@yahoo.com>
Date:   Sat Sep 14 14:37:40 2024 -0400

    Merge pull request #53 from Joedahms/ndjson-output

    Ndjson output

commit 2285d33ab087bf5a70e3702618bbcfb55149639a
Author: Joedahms <dahms.joejoe@gmail.com>
Date:   Sat Sep 14 14:18:14 2024 -0400

    ./run URL_FILE now passes syntax checker

commit 3d19c153fd33545d82e10647d12936e4f75e0e13
Author: Joedahms <dahms.joejoe@gmail.com>
Date:   Fri Sep 13 16:38:07 2024 -0400

    can output ndjson of all metrics. need to update documentation as I added new classes

commit 0162b5f8d33dfd09d6b4f46ba6ba024b79259638
Author: Joedahms <dahms.joejoe@gmail.com>
Date:   Fri Sep 13 12:28:50 2024 -0400

    Integrated my ndjson testing into main.ts

commit 0fe7a9660157709c8efc6ad95d860aea66764ca1
Merge: 7a5dc5c 4d6e3a2
Author: Joedahms <dahms.joejoe@gmail.com>
Date:   Fri Sep 13 12:20:48 2024 -0400

    Resolved merge conflicts with main after pull

commit 7a5dc5cec4b3f4bcbe32be0a33ba302a911a83f5
Author: Joedahms <dahms.joejoe@gmail.com>
Date:   Thu Sep 12 19:30:08 2024 -0400

    Started playing around with NDJSON and outputting it to stdout

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,11 +1,10 @@
 #!/bin/bash
-# Need to print out whether a helpful error if something fails
 
-# rm *.js # Remove all JavaScript files
-export LOG_LEVEL=0   # Default log level is 0
-export LOG_LEVEL=2   # here for testing
-if [ $# == 1 ]; then # One command line argument
-  if [ $1 == "install" ]; then
+#tsc
+export LOG_LEVEL=0             # Default log level is 0
+export LOG_LEVEL=2             # here for testing
+if [ $# == 1 ]; then           # One command line argument
+  if [ $1 == "install" ]; then # Install
     echo "Installing required packages..."
     npm install # Install packages in userland
     echo "Installed required packages"
@@ -13,16 +12,13 @@ if [ $# == 1 ]; then # One command line argument
     echo "Current log level is $LOG_LEVEL"
     echo "You chose test"
     # Call the test suite here
-  else
-    echo "Current log level is $LOG_LEVEL"
-    echo "You passed $1" # URL_FILE
-    echo "Compiling TypeScript files..."
-    npx tsc
-    if [ $? -ne 0 ]; then
+  else                    # URL_FILE
+    tsc                   # Compile TypeScript files to JavaScript
+    if [ $? -ne 0 ]; then # ?
       echo "TypeScript compilation failed. Exiting..."
       exit 1
     fi
-    echo "Running JaveScript file..."
+    # Can't echo anything here or syntax checker fails
     node src/main.js $1
   fi
 else # Not one command line argument
